name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHIX_CACHE: smaug123

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Use Cachix
        uses: cachix/cachix-action@v15
        with:
          name: ${{ env.CACHIX_CACHE }}

      - name: Run tests
        run: nix develop --command bun test

      - name: Check Nix formatting
        run: nix develop --command alejandra --check .

      - name: Nix build
        run: nix build

  all-required-checks-complete:
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: G-Research/common-actions/check-required-lite@2b7dc49cb14f3344fbe6019c14a31165e258c059
        with:
          needs-context: ${{ toJSON(needs) }}
